# Subtree flake generation for worker worktrees
{lib}: {
  # Generate the content of a subtree flake.nix file
  # This flake will be used by sibling worktrees
  generateSubtreeFlakeContent = {
    languages,
    mcps,
    tools,
    devshellsUrl ? "github:Ba-So/nix-devshells",
  }: let
    # Filter out task-master from MCPs for subtree
    filteredMcps = builtins.filter (m: m != "claude-task-master") mcps;

    # Convert lists to Nix literal strings for the flake
    languagesNix = lib.concatStringsSep " " (map (l: ''"${l}"'') languages);
    mcpsNix = lib.concatStringsSep " " (map (m: ''"${m}"'') filteredMcps);
  in ''
    # GENERATED by nix-devshells worktree mode - do not edit manually
    # Subtree shell for worker agents (without task-master)
    {
      inputs = {
        nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
        flake-utils.url = "github:numtide/flake-utils";
        devshells.url = "${devshellsUrl}";
      };

      outputs = { nixpkgs, flake-utils, devshells, ... }:
        flake-utils.lib.eachDefaultSystem (system: {
          devShells.default = devshells.lib.''${system}.composeShell {
            type = "subtree";
            languages = [${languagesNix}];
            mcps = [${mcpsNix}];
            tools = "${tools}";
          };
        });
    }
  '';
}
