# Source filtering for worktree flakes
_: {
  # Create a filtered source for worktree flakes
  # Excludes generated directories to avoid copying them to the nix store
  # With sibling pattern, there's no nested mainDir to filter
  mkWorktreeSource = {
    src,
    extraExcludes ? [],
  }: let
    excludedNames =
      [
        ".shared" # Generated by worktree mode
        ".orchestrator" # Generated by worktree mode
        ".direnv" # direnv cache
        "target" # Common build directory (Rust, etc.)
        "node_modules" # Node.js dependencies
        "__pycache__" # Python cache
        ".mypy_cache" # Mypy cache
        ".pytest_cache" # Pytest cache
      ]
      ++ extraExcludes;
  in
    builtins.path {
      path = src;
      name = "worktree-source";
      filter = path: _type: let
        name = baseNameOf path;
        # Always include essential flake files at the root
        isFlakeFile = name == "flake.nix" || name == "flake.lock" || name == ".envrc";
      in
        isFlakeFile || !(builtins.elem name excludedNames);
    };
}
