# Worktree mode support
# Generates subtree flakes and helper commands for multi-agent workflows
#
# Design: Sibling worktree pattern
# ================================
# The main repo contains the orchestrator, and worktrees are created as siblings:
#
#   myproject/                  # Main git repo + orchestrator
#   ├── .shared/                # Shared config for sibling worktrees
#   ├── .orchestrator/          # Orchestrator MCP config
#   └── <source code>
#
#   ../myproject-feature-x/     # Sibling worktree (not nested)
#   ../myproject-feature-y/     # Another sibling worktree
#
{
  pkgs,
  lib,
  system,
}: rec {
  # Generate the content of a subtree flake.nix file
  # This flake will be used by sibling worktrees
  generateSubtreeFlakeContent = {
    languages,
    mcps,
    tools,
    devshellsUrl ? "github:Ba-So/nix-devshells",
  }: let
    # Filter out task-master from MCPs for subtree
    filteredMcps = builtins.filter (m: m != "claude-task-master") mcps;

    # Convert lists to Nix literal strings for the flake
    languagesNix = lib.concatStringsSep " " (map (l: ''"${l}"'') languages);
    mcpsNix = lib.concatStringsSep " " (map (m: ''"${m}"'') filteredMcps);
  in ''
    # GENERATED by nix-devshells worktree mode - do not edit manually
    # Subtree shell for worker agents (without task-master)
    {
      inputs = {
        nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
        flake-utils.url = "github:numtide/flake-utils";
        devshells.url = "${devshellsUrl}";
      };

      outputs = { nixpkgs, flake-utils, devshells, ... }:
        flake-utils.lib.eachDefaultSystem (system: {
          devShells.default = devshells.lib.''${system}.composeShell {
            type = "subtree";
            languages = [${languagesNix}];
            mcps = [${mcpsNix}];
            tools = "${tools}";
          };
        });
    }
  '';

  # Generate shared CLAUDE.md content for worker agents
  generateSharedClaudeMd = ''
    # Worker Agent

    You are a worker agent in a multi-agent worktree workflow. You work on isolated feature branches while an orchestrator coordinates tasks.

    ## Your Environment

    - **Location**: Sibling worktree (`../<project>-<branch>/`)
    - **Main project**: `../<project>/`
    - **Branch**: You're on a dedicated feature branch
    - **Code index**: Shared with main project (read-only)

    ## Your Role

    You focus on **implementation**. The orchestrator handles task coordination.

    ### What You Do
    - Implement assigned features/fixes
    - Write tests for your changes
    - Commit completed work with clear messages
    - Keep changes focused on the assigned task

    ### What You Don't Do
    - Create or manage tasks (no task-master access)
    - Work on unrelated code
    - Merge branches (orchestrator handles this)

    ## Git Workflow

    ```bash
    # Check your branch
    git branch

    # Stage and commit your work
    git add <files>
    git commit -m "feat: description of change"

    # Push when ready for review
    git push -u origin <branch>
    ```

    ## Communication

    Your commits are your primary communication. Write clear commit messages:
    - `feat:` - New feature
    - `fix:` - Bug fix
    - `refactor:` - Code restructuring
    - `test:` - Adding tests
    - `docs:` - Documentation

    When blocked or need clarification, note it in a commit or leave a TODO comment.

    ## Available Tools

    - **codanna**: Code intelligence (shared index from main project)
    - **serena**: Project analysis (if configured)
    - Other MCPs as configured (except task-master)
  '';

  # Generate orchestrator skill commands for .claude/commands/
  # These enable the hybrid orchestration workflow
  generateOrchestratorSkills = {
    # Main orchestration entry point
    "orchestrate" = ''
      # Orchestrator

      Orchestrate tasks using worktree isolation with parallel agents.

      Tasks to orchestrate: $ARGUMENTS

      ## Architecture

      ```
      ┌─────────────────────────────────────────────────────────────┐
      │  ORCHESTRATOR (this session, main worktree)                 │
      │                                                             │
      │  Phase 1: Setup worktrees                                   │
      │  Phase 2: Spawn coding agents (parallel)                    │
      │  Phase 3: Collect results                                   │
      │  Phase 4: Spawn review agents (parallel)                    │
      │  Phase 5: Process verdicts → merge or iterate               │
      │                                                             │
      │         │              │              │                     │
      │         ▼              ▼              ▼                     │
      │  ┌──────────┐   ┌──────────┐   ┌──────────┐                │
      │  │ Worker A │   │ Worker B │   │ Worker C │                │
      │  │ (bg)     │   │ (bg)     │   │ (bg)     │                │
      │  └──────────┘   └──────────┘   └──────────┘                │
      └─────────────────────────────────────────────────────────────┘
      ```

      ## Worktree Naming

      Worktrees are created as **siblings** of the main project:
      - Main project: `/path/to/myproject/`
      - Worktree for task 3: `/path/to/myproject-task-3/`

      Pattern: `../<project>-task-<id>/`

      ## Workflow

      ### Phase 1: Setup Worktrees

      Parse task IDs from $ARGUMENTS (comma or space separated).

      For each task ID:
      ```bash
      task-master set-status --id=<id> --status=in-progress
      task-master show <id>  # Get task details, save for agent prompt
      worktree-new task-<id> # Creates ../<project>-task-<id>/
      ```

      Record:
      - Task ID
      - Task title and description
      - Worktree absolute path

      ### Phase 2: Spawn Coding Agents (Parallel)

      **CRITICAL**: Spawn ALL agents in a SINGLE message for true parallelism.

      Use Task tool with `run_in_background=true` for each task:

      ```
      Task(subagent_type="general-purpose", run_in_background=true, prompt="
      CODING AGENT - Task <id>: <title>

      ## Working Directory
      FIRST COMMAND: cd <absolute-path-to-worktree>
      You MUST cd before any other operation.

      ## Task Requirements
      <full description from task-master>

      ## Instructions
      1. cd to working directory (MANDATORY FIRST STEP)
      2. Implement the required changes
      3. Run tests/linting if available
      4. Stage and commit: git add <specific-files> && git commit -m '<type>: <summary>'
      5. Push: git push -u origin task-<id>

      ## Commit Message Format
      - feat: new feature
      - fix: bug fix
      - refactor: code restructuring
      - test: adding tests

      ## Output Format (REQUIRED)
      Respond with ONLY this JSON:
      {
        \"task_id\": \"<id>\",
        \"status\": \"complete\" | \"blocked\",
        \"files_changed\": [\"path/to/file1\", \"path/to/file2\"],
        \"summary\": \"Brief description of changes made\",
        \"tests_passed\": true | false | \"no tests\",
        \"blocked_reason\": \"Only if status is blocked\"
      }
      ")
      ```

      Record agent IDs for each task.

      ### Phase 3: Collect Results

      Wait for all coding agents to complete:
      ```
      TaskOutput(task_id="<agent-id>", block=true, timeout=600000)
      ```

      For each completed agent, verify git state:
      ```bash
      PROJECT_NAME=$(basename "$(pwd)")
      WORKTREE="../''${PROJECT_NAME}-task-<id>"

      # Check for uncommitted changes (should be empty)
      git -C "$WORKTREE" status --porcelain

      # Check branch was pushed
      git fetch origin task-<id> 2>/dev/null && echo "Pushed" || echo "NOT PUSHED"

      # Show commits for review context
      git -C "$WORKTREE" log main..HEAD --oneline
      ```

      Categorize tasks:
      - **Ready for review**: status=complete, no uncommitted changes, branch pushed
      - **Blocked**: status=blocked or uncommitted changes or not pushed

      For blocked tasks:
      ```bash
      task-master update-subtask --id=<id> --prompt="Blocked: <reason>"
      ```

      ### Phase 4: Spawn Review Agents (Parallel)

      **CRITICAL**: Spawn ALL review agents in a SINGLE message for true parallelism.

      Only review tasks that are "ready for review".

      ```
      Task(subagent_type="general-purpose", run_in_background=true, prompt="
      REVIEW AGENT - Task <id>: <title>

      ## Working Directory
      FIRST COMMAND: cd <absolute-path-to-worktree>

      ## Task Requirements
      <full description from task-master>

      ## Changes to Review
      Files changed: <list from coding agent output>
      Summary: <summary from coding agent output>

      ## Review Checklist
      1. **Requirements**: Does implementation match task requirements?
      2. **Correctness**: Are there obvious bugs or logic errors?
      3. **Code Quality**: Does it follow existing patterns in the codebase?
      4. **Safety**: Any security issues, resource leaks, or error handling gaps?
      5. **Tests**: If tests exist, do they pass? If new code, are tests needed?

      ## Review Process
      1. cd to working directory
      2. Read the changed files
      3. Check git diff: git diff main..HEAD
      4. Run tests if available
      5. Evaluate against checklist

      ## Output Format (REQUIRED)
      Respond with ONLY this JSON:
      {
        \"task_id\": \"<id>\",
        \"verdict\": \"APPROVE\" | \"CHANGES_REQUESTED\",
        \"checklist\": {
          \"requirements_met\": true | false,
          \"no_bugs\": true | false,
          \"follows_patterns\": true | false,
          \"no_safety_issues\": true | false,
          \"tests_ok\": true | false | \"not applicable\"
        },
        \"issues\": [
          {\"file\": \"path/to/file\", \"line\": 42, \"issue\": \"Description of problem\"}
        ],
        \"summary\": \"Brief overall assessment\"
      }
      ")
      ```

      Record review agent IDs.

      ### Phase 5: Process Verdicts

      Wait for all review agents:
      ```
      TaskOutput(task_id="<review-agent-id>", block=true, timeout=300000)
      ```

      #### For APPROVED tasks:

      ```bash
      PROJECT_NAME=$(basename "$(pwd)")

      # Merge from worktree
      git fetch "../''${PROJECT_NAME}-task-<id>" HEAD:task-<id>
      git merge task-<id> --no-ff -m "Merge task-<id>: <summary>"

      # Verify merge succeeded
      if [ $? -eq 0 ]; then
        task-master set-status --id=<id> --status=done
        worktree-remove task-<id>
        echo "Task <id> merged and cleaned up"
      else
        echo "MERGE CONFLICT - requires manual resolution"
        task-master update-subtask --id=<id> --prompt="Merge conflict - needs manual resolution"
      fi
      ```

      #### For CHANGES_REQUESTED tasks:

      Track iteration count (max 3).

      If iterations < 3:
      ```bash
      task-master update-subtask --id=<id> --prompt="Review iteration <n>: <issues summary>"
      ```

      Then spawn fix agents (parallel) - see Phase 6.

      If iterations >= 3:
      ```bash
      task-master set-status --id=<id> --status=blocked
      task-master update-subtask --id=<id> --prompt="Blocked: max iterations (3) exceeded. Issues: <summary>"
      echo "Task <id> blocked - requires manual intervention"
      # Keep worktree for manual inspection
      ```

      ### Phase 6: Fix Iteration (if needed)

      For tasks with CHANGES_REQUESTED and iterations < 3:

      **Spawn fix agents in parallel:**

      ```
      Task(subagent_type="general-purpose", run_in_background=true, prompt="
      FIX AGENT - Task <id>: <title> (Iteration <n>)

      ## Working Directory
      FIRST COMMAND: cd <absolute-path-to-worktree>

      ## Original Requirements
      <full description from task-master>

      ## Issues to Fix
      <issues array from review agent, formatted as list>

      ## Instructions
      1. cd to working directory
      2. Address each issue listed above
      3. Do NOT change unrelated code
      4. Commit fixes: git add <files> && git commit -m 'fix: address review feedback'
      5. Push: git push origin task-<id>

      ## Output Format (REQUIRED)
      {
        \"task_id\": \"<id>\",
        \"iteration\": <n>,
        \"status\": \"complete\" | \"blocked\",
        \"fixes_applied\": [\"Description of fix 1\", \"Description of fix 2\"],
        \"issues_unresolved\": [\"Any issues that could not be fixed\"]
      }
      ")
      ```

      After fix agents complete → return to Phase 3 (collect) → Phase 4 (review).

      ## Error Handling

      | Situation | Action |
      |-----------|--------|
      | Coding agent fails/crashes | Mark task `blocked`, keep worktree, log error |
      | Review agent fails/crashes | Retry once, then mark `blocked` |
      | Merge conflict | Do NOT auto-resolve, mark `blocked`, alert user |
      | Agent timeout (10min) | Mark task `blocked`, keep worktree |
      | Max iterations exceeded | Mark `blocked`, keep worktree for inspection |

      ## Cleanup Summary

      | Verdict | Worktree | Branch | Task Status |
      |---------|----------|--------|-------------|
      | APPROVED + merged | Remove | Keep (merged) | `done` |
      | BLOCKED | Keep | Keep | `blocked` |
      | CHANGES_REQUESTED (iterating) | Keep | Keep | `in-progress` |

      ## Final Report

      After all tasks processed:
      ```bash
      echo "=== Orchestration Complete ==="
      task-master list
      git log --oneline -10
      worktree-status
      ```
    '';

    # Spawn workers - quick command
    "spawn-workers" = ''
      # Spawn Workers

      Create worktrees and spawn parallel coding agents for tasks: $ARGUMENTS

      ## Steps

      ### 1. Parse Tasks
      Split $ARGUMENTS into task IDs.

      ### 2. Setup
      ```bash
      PROJECT_ROOT=$(pwd)
      PROJECT_NAME=$(basename "$PROJECT_ROOT")
      ```

      ### 3. Create Worktrees
      For each task ID:
      ```bash
      task-master show <id>
      worktree-new task-<id>
      ```

      ### 4. Spawn Agents in Parallel

      **Send ONE message with ALL Task calls:**

      ```
      Task(subagent_type="general-purpose", run_in_background=true, prompt="
      CODING AGENT - Task <id>

      Working directory: ''${PROJECT_ROOT}/../''${PROJECT_NAME}-task-<id>
      FIRST COMMAND: cd <working directory>

      ## Task
      <title and description from task-master>

      ## Instructions
      1. cd to working directory (MANDATORY)
      2. Implement changes
      3. Commit: git commit -m 'feat: <description>'
      4. Push: git push -u origin task-<id>

      ## Output
      {
        \"task_id\": \"<id>\",
        \"status\": \"complete|blocked\",
        \"files_changed\": [...],
        \"summary\": \"...\",
        \"ready_for_review\": true|false
      }
      ")
      ```

      ### 5. Report
      Return agent IDs and how to check progress.
    '';

    # Collect results from background agents
    "collect-results" = ''
      # Collect Results

      Gather results from background worker agents: $ARGUMENTS

      ## Steps

      ### 1. Check Each Agent
      ```
      TaskOutput(task_id="<agent-id>", block=false, timeout=5000)
      ```

      Categorize: Completed / Running / Failed

      ### 2. Wait for Remaining (optional)
      ```
      TaskOutput(task_id="<agent-id>", block=true, timeout=600000)
      ```

      ### 3. Verify Git State
      ```bash
      PROJECT_NAME=$(basename "$(pwd)")
      for id in <task-ids>; do
        WORKTREE="../''${PROJECT_NAME}-task-''${id}"
        git -C "$WORKTREE" log --oneline -3
        git fetch origin "task-''${id}" 2>/dev/null && echo "Pushed" || echo "Not pushed"
      done
      ```

      ### 4. Queue Reviews
      For tasks with `ready_for_review: true`, proceed to /review-and-merge.

      ### 5. Summary
      Report status of all tasks.
    '';

    # Review and merge completed work
    "review-and-merge" = ''
      # Review and Merge

      Review completed work and merge approved changes: $ARGUMENTS

      ## Steps

      ### 1. Identify Tasks
      Use provided task IDs or find ready worktrees:
      ```bash
      PROJECT_NAME=$(basename "$(pwd)")
      for wt in ../''${PROJECT_NAME}-task-*; do
        TASK_ID=$(echo "$wt" | grep -oE '[0-9]+$')
        AHEAD=$(git -C "$wt" rev-list main..HEAD --count 2>/dev/null)
        [ "$AHEAD" -gt 0 ] && echo "Task $TASK_ID: $AHEAD commits"
      done
      ```

      ### 2. Review Each Task

      ```bash
      task-master show <id>
      git -C "../project-task-<id>" diff main...HEAD --stat
      ```

      Spawn review agent:
      ```
      Task(subagent_type="general-purpose", prompt="
      REVIEW AGENT - Task <id>

      cd <worktree>

      ## Requirements
      <from task-master>

      ## Review Checklist
      - [ ] Implements requirements
      - [ ] No bugs
      - [ ] Follows style
      - [ ] Tests pass

      Output: APPROVE | CHANGES_REQUESTED
      ")
      ```

      ### 3. Process Verdict

      **If APPROVED:**
      ```bash
      git fetch "../project-task-<id>" HEAD:task-<id>
      git merge task-<id> --no-ff -m "Merge task-<id>: <summary>"
      task-master set-status --id=<id> --status=done
      worktree-remove task-<id>
      ```

      **If CHANGES_REQUESTED:**
      Spawn fix agent with feedback, then re-review.

      ### 4. Summary
      ```bash
      git log --oneline -10
      task-master list
      ```
    '';

    # Iteration loop for review-fix cycles
    "iteration-loop" = ''
      # Iteration Loop

      Run review-fix iterations until approved: $ARGUMENTS

      ## Flow

      ```
      CODING ──▶ REVIEW ──▶ APPROVED? ──▶ EXIT
         ▲         │
         │         │ CHANGES_REQUESTED
         └─────────┘
      ```

      ## Steps

      ### 1. Initialize
      ```bash
      task-master show $ARGUMENTS
      iteration=1
      max_iterations=3
      ```

      ### 2. Code Phase
      ```
      Task(subagent_type="general-purpose", prompt="
      CODING AGENT - Iteration {iteration}
      Task: $ARGUMENTS
      Previous feedback: <if any>
      Implement fixes based on feedback.
      ")
      ```

      ### 3. Review Phase
      ```
      Task(subagent_type="general-purpose", prompt="
      REVIEW AGENT - Iteration {iteration}
      Check if issues resolved. Find new issues.
      Output: APPROVE or CHANGES_REQUESTED
      ")
      ```

      ### 4. Decision
      - **APPROVE**: Mark done, exit
      - **CHANGES_REQUESTED + iteration < max**: Loop back
      - **CHANGES_REQUESTED + iteration >= max**: Mark blocked, alert user

      ### 5. Logging
      ```bash
      task-master update-subtask --id=$ARGUMENTS --prompt="Iteration {n}: <verdict>"
      ```
    '';
  };

  # Generate orchestrator CLAUDE.md content
  generateOrchestratorClaudeMd = ''
    # Orchestrator Agent

    You are the orchestrator in a multi-agent worktree workflow. You coordinate tasks and manage parallel work streams across sibling worktrees.

    ## Project Structure

    ```
    ./                              # Main repo (you are here)
    ├── .shared/                    # Shared config for workers
    │   └── .codanna/               # Shared code index
    ├── .orchestrator/              # Your MCP config
    └── <source code>

    ../<project>-feature-x/         # Worker worktree (sibling)
    ../<project>-feature-y/         # Another worker worktree
    ```

    ## Your Role

    You are the **coordinator**. Workers handle implementation.

    ### What You Do
    - Break down work into tasks (task-master)
    - Create worktrees for parallel work streams
    - Monitor progress across worktrees
    - Review and merge completed work
    - Resolve conflicts and blockers

    ### What Workers Do
    - Implement assigned tasks
    - Commit changes to their branch
    - Stay focused on their assigned work

    ## Worktree Commands

    ```bash
    # Create a new worktree for a feature
    worktree-new feature-auth
    # Creates: ../<project>-feature-auth/

    # Check status of all worktrees
    worktree-status

    # Remove a completed worktree
    worktree-remove feature-auth
    ```

    ## Task Management

    Use task-master MCP to coordinate work:

    ```
    # View tasks
    task-master list
    task-master next

    # Create tasks
    task-master add-task --prompt="Implement user authentication"

    # Update status
    task-master set-status --id=1 --status=in-progress
    task-master set-status --id=1 --status=done
    ```

    ## Typical Workflow

    ### 1. Plan Work
    ```bash
    # Analyze complexity if needed
    task-master analyze-complexity --research

    # Create tasks from requirements
    task-master add-task --prompt="..." --research
    ```

    ### 2. Spawn Workers
    ```bash
    # Create worktree for each major task
    worktree-new feature-auth
    worktree-new feature-dashboard

    # Workers activate with: cd ../<project>-<branch> && direnv allow
    ```

    ### 3. Monitor Progress
    ```bash
    # Check task status
    task-master list

    # Review worker commits
    git log ../<project>-feature-auth

    # Check worktree status
    worktree-status
    ```

    ### 4. Complete Work
    ```bash
    # Merge completed feature
    git merge feature-auth

    # Clean up
    worktree-remove feature-auth
    task-master set-status --id=1 --status=done
    ```

    ## Available Tools

    - **task-master**: Task creation, assignment, and tracking (orchestrator only)
    - **codanna**: Code intelligence and navigation
    - **serena**: Project analysis (if configured)
    - Other configured MCPs

    ## Notes

    - Workers do NOT have task-master access - coordinate through you
    - The shared codanna index is at `.shared/.codanna/`
    - Workers see the same code index but work on isolated branches
  '';

  # Create worktree helper scripts as actual executables
  # Uses sibling worktree pattern: worktrees are created as siblings of the main repo
  mkWorktreeScripts = _:
    pkgs.stdenvNoCC.mkDerivation {
      name = "worktree-scripts";
      dontUnpack = true;
      buildInputs = [pkgs.git];

      installPhase = ''
              mkdir -p $out/bin

              # worktree-new script
              cat > $out/bin/worktree-new << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        branch="''${1:-}"
        if [ -z "$branch" ]; then
          echo "Usage: worktree-new <branch-name>"
          echo "Creates a new git worktree as a sibling directory"
          echo ""
          echo "Example: worktree-new feature-auth"
          echo "  Creates: ../<project>-feature-auth/"
          exit 1
        fi

        # Check we're in the project root (where .shared/ lives)
        if [ ! -d ".shared" ]; then
          echo "Error: .shared/ directory not found."
          echo "Run this command from the project root (orchestrator directory)."
          exit 1
        fi

        # Check this is a git repository
        if [ ! -d ".git" ]; then
          echo "Error: Current directory is not a git repository."
          exit 1
        fi

        # Get project name from current directory
        project_name=$(basename "$(pwd)")
        worktree_path="../''${project_name}-''${branch}"

        # Check if worktree already exists
        if [ -d "$worktree_path" ]; then
          echo "Error: Directory $worktree_path already exists"
          exit 1
        fi

        # Create the git worktree as a sibling
        echo "Creating git worktree for branch '$branch'..."
        if git worktree add "$worktree_path" -b "$branch" 2>/dev/null || git worktree add "$worktree_path" "$branch"; then
          echo "  Created worktree at $worktree_path"
        else
          echo "Error: Failed to create worktree"
          exit 1
        fi

        # Create .envrc in worktree pointing back to .shared
        cat > "$worktree_path/.envrc" << ENVRC_EOF
        # Use the shared subtree flake for worker agents
        use flake ../$project_name/.shared --impure
        ENVRC_EOF
        echo "  Created $worktree_path/.envrc"

        # Create symlinks to shared config
        ln -sf "../$project_name/.shared/.mcp.json" "$worktree_path/.mcp.json"
        echo "  Linked .mcp.json -> ../$project_name/.shared/.mcp.json"

        ln -sf "../$project_name/.shared/CLAUDE.md" "$worktree_path/CLAUDE.md"
        echo "  Linked CLAUDE.md -> ../$project_name/.shared/CLAUDE.md"

        echo ""
        echo "Worktree '$branch' created successfully!"
        echo "  Path: $worktree_path"
        echo "  Shell: use flake ../$project_name/.shared --impure"

        # Auto-allow direnv if available
        if command -v direnv &> /dev/null; then
          echo ""
          echo "Allowing direnv in worktree..."
          direnv allow "$worktree_path"
          echo "  direnv allowed for $worktree_path"
        else
          echo ""
          echo "To activate: cd $worktree_path && direnv allow"
        fi
        SCRIPT_EOF
              chmod +x $out/bin/worktree-new

              # worktree-status script
              cat > $out/bin/worktree-status << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        project_name=$(basename "$(pwd)")

        echo "=== Project: $project_name ==="
        echo "  Location: $(pwd)"
        echo ""

        echo "=== Git Worktrees ==="
        if [ -d ".git" ]; then
          git worktree list
        else
          echo "  Error: Current directory is not a git repository"
        fi
        echo ""

        echo "=== Shared Resources ==="
        if [ -d ".shared" ]; then
          echo "  .shared/flake.nix: $([ -f .shared/flake.nix ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/.mcp.json: $([ -f .shared/.mcp.json ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/CLAUDE.md: $([ -f .shared/CLAUDE.md ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/.codanna/: $([ -d .shared/.codanna ] && echo 'present' || echo 'MISSING')"
          if [ -d .shared/.codanna ]; then
            index_size=$(du -sh .shared/.codanna 2>/dev/null | cut -f1)
            echo "    Index size: $index_size"
          fi
        else
          echo "  .shared/ directory: MISSING"
        fi
        echo ""

        echo "=== Orchestrator ==="
        echo "  .orchestrator/.mcp.json: $([ -f .orchestrator/.mcp.json ] && echo 'present' || echo 'MISSING')"
        if [ -L ".mcp.json" ]; then
          echo "  .mcp.json: symlink -> $(readlink .mcp.json)"
        elif [ -f ".mcp.json" ]; then
          echo "  .mcp.json: regular file"
        else
          echo "  .mcp.json: MISSING"
        fi
        echo ""

        echo "=== Environment ==="
        echo "  CODANNA_INDEX_DIR: ''${CODANNA_INDEX_DIR:-not set}"
        SCRIPT_EOF
              chmod +x $out/bin/worktree-status

              # worktree-remove script
              cat > $out/bin/worktree-remove << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        branch="''${1:-}"
        if [ -z "$branch" ]; then
          echo "Usage: worktree-remove <branch-name>"
          echo "Removes a sibling git worktree"
          exit 1
        fi

        project_name=$(basename "$(pwd)")
        worktree_path="../''${project_name}-''${branch}"

        if [ ! -d "$worktree_path" ]; then
          echo "Error: Worktree directory $worktree_path does not exist"
          exit 1
        fi

        # Run git worktree remove
        echo "Removing git worktree '$branch'..."
        git worktree remove "$worktree_path" --force
        echo "  Removed worktree at $worktree_path"

        # Optionally remove the branch
        read -p "Also delete branch '$branch'? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
          git branch -D "$branch" 2>/dev/null && echo "  Deleted branch '$branch'" || echo "  Could not delete branch (may not exist or be checked out elsewhere)"
        fi
        SCRIPT_EOF
              chmod +x $out/bin/worktree-remove
      '';
    };

  # Default worktree scripts
  worktreeScripts = mkWorktreeScripts {};

  # Shell hook for worktree mode (orchestrator)
  # Sets up directories and generates config files
  # Uses sibling worktree pattern - main repo is the orchestrator, worktrees are siblings
  worktreeShellHook = {
    mcpConfigOrchestrator,
    mcpConfigShared,
    languages,
    mcps,
    tools,
    devshellsUrl ? "github:Ba-So/nix-devshells",
  }: let
    subtreeFlakeContent = generateSubtreeFlakeContent {
      inherit languages mcps tools devshellsUrl;
    };
    sharedClaudeMd = generateSharedClaudeMd;
    orchestratorClaudeMd = generateOrchestratorClaudeMd;
    orchestratorSkills = generateOrchestratorSkills;
  in ''
    # Worktree mode setup (sibling pattern)
    _setup_worktree_mode() {
      local project_root
      project_root="$(pwd)"

      # Verify this is a git repository
      if [ ! -d ".git" ]; then
        echo "  Warning: Not a git repository. Worktree commands won't work."
        echo "  Initialize git first: git init"
      fi

      # Create .shared directory
      if [ ! -d ".shared" ]; then
        mkdir -p .shared/.codanna
        echo "  Created .shared/ directory"
      fi

      # Generate .shared/flake.nix
      cat > .shared/flake.nix << 'SUBTREE_FLAKE_EOF'
    ${subtreeFlakeContent}
    SUBTREE_FLAKE_EOF
      echo "  Generated .shared/flake.nix"

      # Copy shared MCP config (without task-master)
      cp ${mcpConfigShared} .shared/.mcp.json
      echo "  Generated .shared/.mcp.json (without task-master)"

      # Generate shared CLAUDE.md
      cat > .shared/CLAUDE.md << 'SHARED_CLAUDE_EOF'
    ${sharedClaudeMd}
    SHARED_CLAUDE_EOF
      echo "  Generated .shared/CLAUDE.md"

      # Create .orchestrator directory
      if [ ! -d ".orchestrator" ]; then
        mkdir -p .orchestrator
        echo "  Created .orchestrator/ directory"
      fi

      # Copy orchestrator MCP config (with task-master)
      cp ${mcpConfigOrchestrator} .orchestrator/.mcp.json

      # Update codanna in orchestrator config to index current directory (.)
      if ${pkgs.jq}/bin/jq -e '.mcpServers.codanna' .orchestrator/.mcp.json &>/dev/null; then
        ${pkgs.jq}/bin/jq '
          .mcpServers.codanna.args = ["serve", ".", "--watch", "--watch-interval", "5"]
        ' .orchestrator/.mcp.json > .orchestrator/.mcp.json.tmp && \
        mv .orchestrator/.mcp.json.tmp .orchestrator/.mcp.json
        echo "  Configured codanna to index current directory"
      fi
      echo "  Generated .orchestrator/.mcp.json (with task-master)"

      # Generate orchestrator CLAUDE.md at root (only if not exists or is a generated file)
      if [ ! -f "CLAUDE.md" ] || grep -q "Orchestrator Agent Instructions" CLAUDE.md 2>/dev/null; then
        cat > CLAUDE.md << 'ORCHESTRATOR_CLAUDE_EOF'
    ${orchestratorClaudeMd}
    ORCHESTRATOR_CLAUDE_EOF
        echo "  Generated CLAUDE.md (orchestrator instructions)"
      else
        echo "  Keeping existing CLAUDE.md (not overwriting user content)"
      fi

      # Generate orchestrator skills in .claude/commands/
      mkdir -p .claude/commands

      cat > .claude/commands/orchestrate.md << 'SKILL_EOF'
    ${orchestratorSkills."orchestrate"}
    SKILL_EOF

      cat > .claude/commands/spawn-workers.md << 'SKILL_EOF'
    ${orchestratorSkills."spawn-workers"}
    SKILL_EOF

      cat > .claude/commands/collect-results.md << 'SKILL_EOF'
    ${orchestratorSkills."collect-results"}
    SKILL_EOF

      cat > .claude/commands/review-and-merge.md << 'SKILL_EOF'
    ${orchestratorSkills."review-and-merge"}
    SKILL_EOF

      cat > .claude/commands/iteration-loop.md << 'SKILL_EOF'
    ${orchestratorSkills."iteration-loop"}
    SKILL_EOF

      echo "  Generated .claude/commands/ (orchestrator skills)"

      # Create symlink from root to orchestrator config
      if [ ! -L ".mcp.json" ] && [ ! -f ".mcp.json" ]; then
        ln -sf .orchestrator/.mcp.json .mcp.json
        echo "  Linked .mcp.json -> .orchestrator/.mcp.json"
      elif [ -L ".mcp.json" ]; then
        # Update existing symlink
        rm .mcp.json
        ln -sf .orchestrator/.mcp.json .mcp.json
        echo "  Updated .mcp.json symlink"
      else
        # .mcp.json exists as regular file - merge configs
        if command -v ${pkgs.jq}/bin/jq &> /dev/null; then
          ${pkgs.jq}/bin/jq -s '.[0] * .[1]' .mcp.json ${mcpConfigOrchestrator} > .mcp.json.new 2>/dev/null || {
            echo "Warning: Failed to merge .mcp.json, keeping existing file"
            rm -f .mcp.json.new
          }
          [ -f .mcp.json.new ] && mv .mcp.json.new .mcp.json && echo "  Merged orchestrator MCP config into .mcp.json"
        fi
      fi

      # Set CODANNA_INDEX_DIR for shared index
      export CODANNA_INDEX_DIR="$project_root/.shared/.codanna"

      echo "  Worktree mode configured (sibling pattern)"
      echo "  CODANNA_INDEX_DIR=$CODANNA_INDEX_DIR"
    }

    _setup_worktree_mode

    echo "  Worktree commands: worktree-new, worktree-status, worktree-remove"
    echo "  Orchestrator skills: /orchestrate, /spawn-workers, /collect-results, /review-and-merge"
  '';

  # Shell hook for subtree mode (worker agents)
  # Minimal setup - just sets CODANNA_INDEX_DIR
  # Sibling pattern: worktree is at ../<project>-<branch>/, main project is at ../<project>/
  subtreeShellHook = ''
    # Subtree mode setup (worker agent in sibling worktree)
    _setup_subtree_mode() {
      local project_root
      project_root="$(pwd)"

      # Find the main project's .shared directory
      # In sibling pattern, we're at ../<project>-<branch>/, main is at ../<project>/
      # The .envrc points to ../<project>/.shared, so we can find it from the flake path

      # Try to find .shared in sibling directories
      local found_shared=""
      for sibling in ../*; do
        if [ -d "$sibling/.shared/.codanna" ]; then
          found_shared="$(cd "$sibling/.shared/.codanna" && pwd)"
          break
        fi
      done

      if [ -n "$found_shared" ]; then
        export CODANNA_INDEX_DIR="$found_shared"
        echo "  Using shared codanna index: $CODANNA_INDEX_DIR"
      else
        echo "  Warning: Shared codanna index not found in sibling directories"
        echo "  Run 'direnv allow' in the main project directory first"
      fi
    }

    _setup_subtree_mode
  '';

  # Create a filtered source for worktree flakes
  # Excludes generated directories to avoid copying them to the nix store
  # With sibling pattern, there's no nested mainDir to filter
  mkWorktreeSource = {
    src,
    extraExcludes ? [],
  }: let
    excludedNames =
      [
        ".shared" # Generated by worktree mode
        ".orchestrator" # Generated by worktree mode
        ".direnv" # direnv cache
        "target" # Common build directory (Rust, etc.)
        "node_modules" # Node.js dependencies
        "__pycache__" # Python cache
        ".mypy_cache" # Mypy cache
        ".pytest_cache" # Pytest cache
      ]
      ++ extraExcludes;
  in
    builtins.path {
      path = src;
      name = "worktree-source";
      filter = path: _type: let
        name = baseNameOf path;
        # Always include essential flake files at the root
        isFlakeFile = name == "flake.nix" || name == "flake.lock" || name == ".envrc";
      in
        isFlakeFile || !(builtins.elem name excludedNames);
    };
}
