# Worktree mode support
# Generates subtree flakes and helper commands for multi-agent workflows
{
  pkgs,
  lib,
  system,
}: rec {
  # Generate the content of a subtree flake.nix file
  # This flake will be used by child worktrees
  generateSubtreeFlakeContent = {
    languages,
    mcps,
    tools,
    devshellsUrl ? "github:Ba-So/nix-devshells",
  }: let
    # Filter out task-master from MCPs for subtree
    filteredMcps = builtins.filter (m: m != "claude-task-master") mcps;

    # Convert lists to Nix literal strings for the flake
    languagesNix = lib.concatStringsSep " " (map (l: ''"${l}"'') languages);
    mcpsNix = lib.concatStringsSep " " (map (m: ''"${m}"'') filteredMcps);
  in ''
    # GENERATED by nix-devshells worktree mode - do not edit manually
    # Subtree shell for worker agents (without task-master)
    {
      inputs = {
        nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
        flake-utils.url = "github:numtide/flake-utils";
        devshells.url = "${devshellsUrl}";
      };

      outputs = { nixpkgs, flake-utils, devshells, ... }:
        flake-utils.lib.eachDefaultSystem (system: {
          devShells.default = devshells.lib.''${system}.composeShell {
            type = "subtree";
            languages = [${languagesNix}];
            mcps = [${mcpsNix}];
            tools = "${tools}";
          };
        });
    }
  '';

  # Generate shared CLAUDE.md content for worker agents
  generateSharedClaudeMd = ''
    # Worker Agent Instructions

    This is a shared configuration for worker agents in a worktree-based multi-agent workflow.

    ## Environment

    - This worktree uses a shared codanna index at `../../.shared/.codanna/`
    - Task coordination is handled by the orchestrator agent
    - MCP servers are available but task-master is only available to the orchestrator

    ## Workflow

    1. Work is assigned by the orchestrator
    2. Complete assigned work in this worktree
    3. Commit changes when work is complete
    4. Report completion to orchestrator

    ## Limitations

    - No direct access to task-master MCP
    - Use the shared codanna index for code navigation
  '';

  # Generate orchestrator CLAUDE.md content
  generateOrchestratorClaudeMd = mainDir: ''
    # Orchestrator Agent Instructions

    You are the orchestrator agent in a multi-agent worktree workflow.

    ## Project Structure

    ```
    ./                      # You are here (project root)
    ├── ${mainDir}/         # Main git checkout (source code lives here)
    ├── worktrees/          # All worker worktrees
    │   ├── feature-x/
    │   └── feature-y/
    ├── .shared/            # Shared config for worker agents
    └── .orchestrator/      # Your MCP config
    ```

    ## Your Responsibilities

    1. **Task Management**: Use task-master MCP to create, assign, and track tasks
    2. **Code Navigation**: Use codanna to understand the codebase (indexes ${mainDir}/)
    3. **Worktree Management**: Create worktrees for parallel work streams
    4. **Coordination**: Monitor worker progress and merge completed work

    ## Available Commands

    - `worktree-new <branch>` - Create a new worktree for a feature/fix
    - `worktree-status` - Show all worktrees and shared resources
    - `worktree-remove <branch>` - Remove a completed worktree

    ## Workflow

    ### Starting New Work
    1. Create a task in task-master
    2. Create a worktree: `worktree-new feature-x`
    3. Assign the task to a worker agent in that worktree

    ### Monitoring Progress
    - Check task status via task-master
    - Review commits in worktrees: `cd <worktree> && git log`
    - Use codanna to understand code changes

    ### Completing Work
    1. Review worker's commits
    2. Merge the branch: `cd ${mainDir} && git merge feature-x`
    3. Remove the worktree: `worktree-remove feature-x`
    4. Mark task as complete

    ## Code Location

    **Important**: The actual source code is in `${mainDir}/`, not the project root.
    When reading/editing code, always use paths like `${mainDir}/src/...`.

    ## MCP Servers

    You have access to:
    - **task-master**: Task management and coordination
    - **codanna**: Code intelligence (indexes ${mainDir}/)
    - Other configured MCPs (serena, etc.)

    Workers do NOT have task-master access - only you coordinate tasks.
  '';

  # Create worktree helper scripts as actual executables
  # mainDir specifies the subdirectory containing the main git checkout
  mkWorktreeScripts = {mainDir ? "main"}:
    pkgs.stdenvNoCC.mkDerivation {
      name = "worktree-scripts";
      dontUnpack = true;
      buildInputs = [pkgs.git];

      installPhase = ''
              mkdir -p $out/bin

              # worktree-new script
              cat > $out/bin/worktree-new << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        # Main git directory (configured at shell creation time)
        MAIN_DIR="${mainDir}"

        branch="''${1:-}"
        if [ -z "$branch" ]; then
          echo "Usage: worktree-new <branch-name>"
          echo "Creates a new git worktree with proper symlinks to shared config"
          echo ""
          echo "Worktrees are created in the 'worktrees/' directory."
          exit 1
        fi

        # Check we're in the project root (where .shared/ lives)
        if [ ! -d ".shared" ]; then
          echo "Error: .shared/ directory not found."
          echo "Run this command from the project root (where flake.nix is)."
          exit 1
        fi

        # Check main git directory exists
        if [ ! -d "$MAIN_DIR/.git" ] && [ ! -f "$MAIN_DIR/.git" ]; then
          echo "Error: $MAIN_DIR/ is not a git repository."
          echo "Expected main git checkout at: $MAIN_DIR/"
          exit 1
        fi

        # Ensure worktrees directory exists
        mkdir -p ./worktrees
        worktree_path="./worktrees/$branch"

        # Check if worktree already exists
        if [ -d "$worktree_path" ]; then
          echo "Error: Directory $worktree_path already exists"
          exit 1
        fi

        # Create the git worktree (run from main dir)
        echo "Creating git worktree for branch '$branch'..."
        cd "$MAIN_DIR"
        if git worktree add "../worktrees/$branch" -b "$branch" 2>/dev/null || git worktree add "../worktrees/$branch" "$branch"; then
          echo "  Created worktree at $worktree_path"
        else
          echo "Error: Failed to create worktree"
          exit 1
        fi
        cd ..

        # Create .envrc in worktree
        cat > "$worktree_path/.envrc" << 'ENVRC_EOF'
        # Use the shared subtree flake for worker agents
        use flake ../../.shared --impure
        ENVRC_EOF
        echo "  Created $worktree_path/.envrc"

        # Create symlinks to shared config
        ln -sf ../../.shared/.mcp.json "$worktree_path/.mcp.json"
        echo "  Linked .mcp.json -> ../../.shared/.mcp.json"

        ln -sf ../../.shared/CLAUDE.md "$worktree_path/CLAUDE.md"
        echo "  Linked CLAUDE.md -> ../../.shared/CLAUDE.md"

        echo ""
        echo "Worktree '$branch' created successfully!"
        echo "  Path: $worktree_path"
        echo "  Shell: use flake ../../.shared --impure"

        # Auto-allow direnv if available
        if command -v direnv &> /dev/null; then
          echo ""
          echo "Allowing direnv in worktree..."
          direnv allow "$worktree_path"
          echo "  direnv allowed for $worktree_path"
        else
          echo ""
          echo "To activate: cd $worktree_path && direnv allow"
        fi
        SCRIPT_EOF
              chmod +x $out/bin/worktree-new

              # worktree-status script
              cat > $out/bin/worktree-status << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        # Main git directory (configured at shell creation time)
        MAIN_DIR="${mainDir}"

        echo "=== Project Structure ==="
        echo "  Main git checkout: $MAIN_DIR/"
        echo ""

        echo "=== Git Worktrees ==="
        if [ -d "$MAIN_DIR/.git" ] || [ -f "$MAIN_DIR/.git" ]; then
          (cd "$MAIN_DIR" && git worktree list)
        else
          echo "  Error: $MAIN_DIR/ is not a git repository"
        fi
        echo ""

        echo "=== Shared Resources ==="
        if [ -d ".shared" ]; then
          echo "  .shared/flake.nix: $([ -f .shared/flake.nix ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/.mcp.json: $([ -f .shared/.mcp.json ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/CLAUDE.md: $([ -f .shared/CLAUDE.md ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/.codanna/: $([ -d .shared/.codanna ] && echo 'present' || echo 'MISSING')"
          if [ -d .shared/.codanna ]; then
            index_size=$(du -sh .shared/.codanna 2>/dev/null | cut -f1)
            echo "    Index size: $index_size"
          fi
        else
          echo "  .shared/ directory: MISSING"
        fi
        echo ""

        echo "=== Orchestrator ==="
        echo "  .orchestrator/.mcp.json: $([ -f .orchestrator/.mcp.json ] && echo 'present' || echo 'MISSING')"
        if [ -L ".mcp.json" ]; then
          echo "  .mcp.json: symlink -> $(readlink .mcp.json)"
        elif [ -f ".mcp.json" ]; then
          echo "  .mcp.json: regular file"
        else
          echo "  .mcp.json: MISSING"
        fi
        echo ""

        echo "=== Environment ==="
        echo "  CODANNA_INDEX_DIR: ''${CODANNA_INDEX_DIR:-not set}"
        SCRIPT_EOF
              chmod +x $out/bin/worktree-status

              # worktree-remove script
              cat > $out/bin/worktree-remove << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        # Main git directory (configured at shell creation time)
        MAIN_DIR="${mainDir}"

        branch="''${1:-}"
        if [ -z "$branch" ]; then
          echo "Usage: worktree-remove <branch-name>"
          echo "Removes a git worktree from the worktrees/ directory"
          exit 1
        fi

        worktree_path="./worktrees/$branch"

        if [ ! -d "$worktree_path" ]; then
          echo "Error: Worktree directory $worktree_path does not exist"
          exit 1
        fi

        # Run git worktree remove from main dir
        echo "Removing git worktree '$branch'..."
        (cd "$MAIN_DIR" && git worktree remove "../worktrees/$branch" --force)
        echo "  Removed worktree at $worktree_path"

        # Optionally remove the branch
        read -p "Also delete branch '$branch'? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
          (cd "$MAIN_DIR" && git branch -D "$branch" 2>/dev/null) && echo "  Deleted branch '$branch'" || echo "  Could not delete branch (may not exist or be checked out elsewhere)"
        fi
        SCRIPT_EOF
              chmod +x $out/bin/worktree-remove
      '';
    };

  # Default worktree scripts (mainDir = "main")
  worktreeScripts = mkWorktreeScripts {};

  # Shell hook for worktree mode (orchestrator)
  # Sets up directories and generates config files
  worktreeShellHook = {
    mcpConfigOrchestrator,
    mcpConfigShared,
    languages,
    mcps,
    tools,
    mainDir ? "main",
    devshellsUrl ? "github:Ba-So/nix-devshells",
  }: let
    subtreeFlakeContent = generateSubtreeFlakeContent {
      inherit languages mcps tools devshellsUrl;
    };
    sharedClaudeMd = generateSharedClaudeMd;
    orchestratorClaudeMd = generateOrchestratorClaudeMd mainDir;
  in ''
    # Worktree mode setup
    _setup_worktree_mode() {
      local project_root
      project_root="$(pwd)"

      # Create .shared directory
      if [ ! -d ".shared" ]; then
        mkdir -p .shared/.codanna
        echo "  Created .shared/ directory"
      fi

      # Generate .shared/flake.nix
      cat > .shared/flake.nix << 'SUBTREE_FLAKE_EOF'
    ${subtreeFlakeContent}
    SUBTREE_FLAKE_EOF
      echo "  Generated .shared/flake.nix"

      # Copy shared MCP config (without task-master)
      cp ${mcpConfigShared} .shared/.mcp.json
      echo "  Generated .shared/.mcp.json (without task-master)"

      # Generate shared CLAUDE.md
      cat > .shared/CLAUDE.md << 'SHARED_CLAUDE_EOF'
    ${sharedClaudeMd}
    SHARED_CLAUDE_EOF
      echo "  Generated .shared/CLAUDE.md"

      # Create .orchestrator directory
      if [ ! -d ".orchestrator" ]; then
        mkdir -p .orchestrator
        echo "  Created .orchestrator/ directory"
      fi

      # Copy orchestrator MCP config (with task-master)
      cp ${mcpConfigOrchestrator} .orchestrator/.mcp.json

      # Update codanna in orchestrator config to index mainDir
      if ${pkgs.jq}/bin/jq -e '.mcpServers.codanna' .orchestrator/.mcp.json &>/dev/null; then
        ${pkgs.jq}/bin/jq --arg mainDir "${mainDir}" '
          .mcpServers.codanna.args = ["serve", $mainDir, "--watch", "--watch-interval", "5"]
        ' .orchestrator/.mcp.json > .orchestrator/.mcp.json.tmp && \
        mv .orchestrator/.mcp.json.tmp .orchestrator/.mcp.json
        echo "  Configured codanna to index ${mainDir}/"
      fi
      echo "  Generated .orchestrator/.mcp.json (with task-master)"

      # Generate orchestrator CLAUDE.md at root
      cat > CLAUDE.md << 'ORCHESTRATOR_CLAUDE_EOF'
    ${orchestratorClaudeMd}
    ORCHESTRATOR_CLAUDE_EOF
      echo "  Generated CLAUDE.md (orchestrator instructions)"

      # Create symlink from root to orchestrator config
      if [ ! -L ".mcp.json" ] && [ ! -f ".mcp.json" ]; then
        ln -sf .orchestrator/.mcp.json .mcp.json
        echo "  Linked .mcp.json -> .orchestrator/.mcp.json"
      elif [ -L ".mcp.json" ]; then
        # Update existing symlink
        rm .mcp.json
        ln -sf .orchestrator/.mcp.json .mcp.json
        echo "  Updated .mcp.json symlink"
      else
        # .mcp.json exists as regular file - merge configs
        if command -v ${pkgs.jq}/bin/jq &> /dev/null; then
          ${pkgs.jq}/bin/jq -s '.[0] * .[1]' .mcp.json ${mcpConfigOrchestrator} > .mcp.json.new 2>/dev/null || {
            echo "Warning: Failed to merge .mcp.json, keeping existing file"
            rm -f .mcp.json.new
          }
          [ -f .mcp.json.new ] && mv .mcp.json.new .mcp.json && echo "  Merged orchestrator MCP config into .mcp.json"
        fi
      fi

      # Set CODANNA_INDEX_DIR for shared index
      export CODANNA_INDEX_DIR="$project_root/.shared/.codanna"

      echo "  Worktree mode configured"
      echo "  CODANNA_INDEX_DIR=$CODANNA_INDEX_DIR"
    }

    _setup_worktree_mode

    echo "  Worktree commands: worktree-new, worktree-status, worktree-remove"
  '';

  # Shell hook for subtree mode (worker agents)
  # Minimal setup - just sets CODANNA_INDEX_DIR
  subtreeShellHook = ''
    # Subtree mode setup (worker agent)
    _setup_subtree_mode() {
      local project_root
      project_root="$(pwd)"

      # Set CODANNA_INDEX_DIR to shared index (grandparent's .shared/.codanna)
      # Worktrees are now at ./worktrees/<branch>/, so .shared is at ../../.shared/
      if [ -d "../../.shared/.codanna" ]; then
        export CODANNA_INDEX_DIR="$(cd ../.. && pwd)/.shared/.codanna"
        echo "  Using shared codanna index: $CODANNA_INDEX_DIR"
      elif [ -d "../.shared/.codanna" ]; then
        # Fallback for legacy worktrees at project root
        export CODANNA_INDEX_DIR="$(cd .. && pwd)/.shared/.codanna"
        echo "  Using shared codanna index: $CODANNA_INDEX_DIR"
      else
        echo "  Warning: Shared codanna index not found"
        echo "  Run 'direnv allow' in the orchestrator directory first"
      fi
    }

    _setup_subtree_mode
  '';

  # Create a filtered source for worktree flakes
  # Excludes mainDir, worktrees/, and generated directories to avoid
  # copying large build artifacts to the nix store during flake evaluation
  mkWorktreeSource = {
    src,
    mainDir ? "main",
    extraExcludes ? [],
  }: let
    excludedNames =
      [
        mainDir # Main git checkout (contains build artifacts)
        "worktrees" # All worktrees
        ".shared" # Generated by worktree mode
        ".orchestrator" # Generated by worktree mode
        ".direnv" # direnv cache
      ]
      ++ extraExcludes;
  in
    builtins.path {
      path = src;
      name = "worktree-source";
      filter = path: _type: let
        name = baseNameOf path;
        # Always include essential flake files at the root
        isFlakeFile = name == "flake.nix" || name == "flake.lock" || name == ".envrc";
      in
        isFlakeFile || !(builtins.elem name excludedNames);
    };
}
