# Worktree mode support
# Generates subtree flakes and helper commands for multi-agent workflows
#
# Design: Sibling worktree pattern
# ================================
# The main repo contains the orchestrator, and worktrees are created as siblings:
#
#   myproject/                  # Main git repo + orchestrator
#   ├── .shared/                # Shared config for sibling worktrees
#   ├── .orchestrator/          # Orchestrator MCP config
#   └── <source code>
#
#   ../myproject-feature-x/     # Sibling worktree (not nested)
#   ../myproject-feature-y/     # Another sibling worktree
#
{
  pkgs,
  lib,
  system,
}: rec {
  # Generate the content of a subtree flake.nix file
  # This flake will be used by sibling worktrees
  generateSubtreeFlakeContent = {
    languages,
    mcps,
    tools,
    devshellsUrl ? "github:Ba-So/nix-devshells",
  }: let
    # Filter out task-master from MCPs for subtree
    filteredMcps = builtins.filter (m: m != "claude-task-master") mcps;

    # Convert lists to Nix literal strings for the flake
    languagesNix = lib.concatStringsSep " " (map (l: ''"${l}"'') languages);
    mcpsNix = lib.concatStringsSep " " (map (m: ''"${m}"'') filteredMcps);
  in ''
    # GENERATED by nix-devshells worktree mode - do not edit manually
    # Subtree shell for worker agents (without task-master)
    {
      inputs = {
        nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
        flake-utils.url = "github:numtide/flake-utils";
        devshells.url = "${devshellsUrl}";
      };

      outputs = { nixpkgs, flake-utils, devshells, ... }:
        flake-utils.lib.eachDefaultSystem (system: {
          devShells.default = devshells.lib.''${system}.composeShell {
            type = "subtree";
            languages = [${languagesNix}];
            mcps = [${mcpsNix}];
            tools = "${tools}";
          };
        });
    }
  '';

  # Generate shared CLAUDE.md content for worker agents
  generateSharedClaudeMd = ''
    # Worker Agent

    You are a worker agent in a multi-agent worktree workflow. You work on isolated feature branches while an orchestrator coordinates tasks.

    ## Your Environment

    - **Location**: Sibling worktree (`../<project>-<branch>/`)
    - **Main project**: `../<project>/`
    - **Branch**: You're on a dedicated feature branch
    - **Code index**: Shared with main project (read-only)

    ## Your Role

    You focus on **implementation**. The orchestrator handles task coordination.

    ### What You Do
    - Implement assigned features/fixes
    - Write tests for your changes
    - Commit completed work with clear messages
    - Keep changes focused on the assigned task

    ### What You Don't Do
    - Create or manage tasks (no task-master access)
    - Work on unrelated code
    - Merge branches (orchestrator handles this)

    ## Git Workflow

    ```bash
    # Check your branch
    git branch

    # Stage and commit your work
    git add <files>
    git commit -m "feat: description of change"

    # Push when ready for review
    git push -u origin <branch>
    ```

    ## Communication

    Your commits are your primary communication. Write clear commit messages:
    - `feat:` - New feature
    - `fix:` - Bug fix
    - `refactor:` - Code restructuring
    - `test:` - Adding tests
    - `docs:` - Documentation

    When blocked or need clarification, note it in a commit or leave a TODO comment.

    ## Available Tools

    - **codanna**: Code intelligence (shared index from main project)
    - **serena**: Project analysis (if configured)
    - Other MCPs as configured (except task-master)
  '';

  # Generate orchestrator CLAUDE.md content
  generateOrchestratorClaudeMd = ''
    # Orchestrator Agent

    You are the orchestrator in a multi-agent worktree workflow. You coordinate tasks and manage parallel work streams across sibling worktrees.

    ## Project Structure

    ```
    ./                              # Main repo (you are here)
    ├── .shared/                    # Shared config for workers
    │   └── .codanna/               # Shared code index
    ├── .orchestrator/              # Your MCP config
    └── <source code>

    ../<project>-feature-x/         # Worker worktree (sibling)
    ../<project>-feature-y/         # Another worker worktree
    ```

    ## Your Role

    You are the **coordinator**. Workers handle implementation.

    ### What You Do
    - Break down work into tasks (task-master)
    - Create worktrees for parallel work streams
    - Monitor progress across worktrees
    - Review and merge completed work
    - Resolve conflicts and blockers

    ### What Workers Do
    - Implement assigned tasks
    - Commit changes to their branch
    - Stay focused on their assigned work

    ## Worktree Commands

    ```bash
    # Create a new worktree for a feature
    worktree-new feature-auth
    # Creates: ../<project>-feature-auth/

    # Check status of all worktrees
    worktree-status

    # Remove a completed worktree
    worktree-remove feature-auth
    ```

    ## Task Management

    Use task-master MCP to coordinate work:

    ```
    # View tasks
    task-master list
    task-master next

    # Create tasks
    task-master add-task --prompt="Implement user authentication"

    # Update status
    task-master set-status --id=1 --status=in-progress
    task-master set-status --id=1 --status=done
    ```

    ## Typical Workflow

    ### 1. Plan Work
    ```bash
    # Analyze complexity if needed
    task-master analyze-complexity --research

    # Create tasks from requirements
    task-master add-task --prompt="..." --research
    ```

    ### 2. Spawn Workers
    ```bash
    # Create worktree for each major task
    worktree-new feature-auth
    worktree-new feature-dashboard

    # Workers activate with: cd ../<project>-<branch> && direnv allow
    ```

    ### 3. Monitor Progress
    ```bash
    # Check task status
    task-master list

    # Review worker commits
    git log ../<project>-feature-auth

    # Check worktree status
    worktree-status
    ```

    ### 4. Complete Work
    ```bash
    # Merge completed feature
    git merge feature-auth

    # Clean up
    worktree-remove feature-auth
    task-master set-status --id=1 --status=done
    ```

    ## Available Tools

    - **task-master**: Task creation, assignment, and tracking (orchestrator only)
    - **codanna**: Code intelligence and navigation
    - **serena**: Project analysis (if configured)
    - Other configured MCPs

    ## Notes

    - Workers do NOT have task-master access - coordinate through you
    - The shared codanna index is at `.shared/.codanna/`
    - Workers see the same code index but work on isolated branches
  '';

  # Create worktree helper scripts as actual executables
  # Uses sibling worktree pattern: worktrees are created as siblings of the main repo
  mkWorktreeScripts = {}:
    pkgs.stdenvNoCC.mkDerivation {
      name = "worktree-scripts";
      dontUnpack = true;
      buildInputs = [pkgs.git];

      installPhase = ''
              mkdir -p $out/bin

              # worktree-new script
              cat > $out/bin/worktree-new << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        branch="''${1:-}"
        if [ -z "$branch" ]; then
          echo "Usage: worktree-new <branch-name>"
          echo "Creates a new git worktree as a sibling directory"
          echo ""
          echo "Example: worktree-new feature-auth"
          echo "  Creates: ../<project>-feature-auth/"
          exit 1
        fi

        # Check we're in the project root (where .shared/ lives)
        if [ ! -d ".shared" ]; then
          echo "Error: .shared/ directory not found."
          echo "Run this command from the project root (orchestrator directory)."
          exit 1
        fi

        # Check this is a git repository
        if [ ! -d ".git" ]; then
          echo "Error: Current directory is not a git repository."
          exit 1
        fi

        # Get project name from current directory
        project_name=$(basename "$(pwd)")
        worktree_path="../''${project_name}-''${branch}"

        # Check if worktree already exists
        if [ -d "$worktree_path" ]; then
          echo "Error: Directory $worktree_path already exists"
          exit 1
        fi

        # Create the git worktree as a sibling
        echo "Creating git worktree for branch '$branch'..."
        if git worktree add "$worktree_path" -b "$branch" 2>/dev/null || git worktree add "$worktree_path" "$branch"; then
          echo "  Created worktree at $worktree_path"
        else
          echo "Error: Failed to create worktree"
          exit 1
        fi

        # Create .envrc in worktree pointing back to .shared
        cat > "$worktree_path/.envrc" << ENVRC_EOF
        # Use the shared subtree flake for worker agents
        use flake ../$project_name/.shared --impure
        ENVRC_EOF
        echo "  Created $worktree_path/.envrc"

        # Create symlinks to shared config
        ln -sf "../$project_name/.shared/.mcp.json" "$worktree_path/.mcp.json"
        echo "  Linked .mcp.json -> ../$project_name/.shared/.mcp.json"

        ln -sf "../$project_name/.shared/CLAUDE.md" "$worktree_path/CLAUDE.md"
        echo "  Linked CLAUDE.md -> ../$project_name/.shared/CLAUDE.md"

        echo ""
        echo "Worktree '$branch' created successfully!"
        echo "  Path: $worktree_path"
        echo "  Shell: use flake ../$project_name/.shared --impure"

        # Auto-allow direnv if available
        if command -v direnv &> /dev/null; then
          echo ""
          echo "Allowing direnv in worktree..."
          direnv allow "$worktree_path"
          echo "  direnv allowed for $worktree_path"
        else
          echo ""
          echo "To activate: cd $worktree_path && direnv allow"
        fi
        SCRIPT_EOF
              chmod +x $out/bin/worktree-new

              # worktree-status script
              cat > $out/bin/worktree-status << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        project_name=$(basename "$(pwd)")

        echo "=== Project: $project_name ==="
        echo "  Location: $(pwd)"
        echo ""

        echo "=== Git Worktrees ==="
        if [ -d ".git" ]; then
          git worktree list
        else
          echo "  Error: Current directory is not a git repository"
        fi
        echo ""

        echo "=== Shared Resources ==="
        if [ -d ".shared" ]; then
          echo "  .shared/flake.nix: $([ -f .shared/flake.nix ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/.mcp.json: $([ -f .shared/.mcp.json ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/CLAUDE.md: $([ -f .shared/CLAUDE.md ] && echo 'present' || echo 'MISSING')"
          echo "  .shared/.codanna/: $([ -d .shared/.codanna ] && echo 'present' || echo 'MISSING')"
          if [ -d .shared/.codanna ]; then
            index_size=$(du -sh .shared/.codanna 2>/dev/null | cut -f1)
            echo "    Index size: $index_size"
          fi
        else
          echo "  .shared/ directory: MISSING"
        fi
        echo ""

        echo "=== Orchestrator ==="
        echo "  .orchestrator/.mcp.json: $([ -f .orchestrator/.mcp.json ] && echo 'present' || echo 'MISSING')"
        if [ -L ".mcp.json" ]; then
          echo "  .mcp.json: symlink -> $(readlink .mcp.json)"
        elif [ -f ".mcp.json" ]; then
          echo "  .mcp.json: regular file"
        else
          echo "  .mcp.json: MISSING"
        fi
        echo ""

        echo "=== Environment ==="
        echo "  CODANNA_INDEX_DIR: ''${CODANNA_INDEX_DIR:-not set}"
        SCRIPT_EOF
              chmod +x $out/bin/worktree-status

              # worktree-remove script
              cat > $out/bin/worktree-remove << 'SCRIPT_EOF'
        #!/usr/bin/env bash
        set -euo pipefail

        branch="''${1:-}"
        if [ -z "$branch" ]; then
          echo "Usage: worktree-remove <branch-name>"
          echo "Removes a sibling git worktree"
          exit 1
        fi

        project_name=$(basename "$(pwd)")
        worktree_path="../''${project_name}-''${branch}"

        if [ ! -d "$worktree_path" ]; then
          echo "Error: Worktree directory $worktree_path does not exist"
          exit 1
        fi

        # Run git worktree remove
        echo "Removing git worktree '$branch'..."
        git worktree remove "$worktree_path" --force
        echo "  Removed worktree at $worktree_path"

        # Optionally remove the branch
        read -p "Also delete branch '$branch'? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
          git branch -D "$branch" 2>/dev/null && echo "  Deleted branch '$branch'" || echo "  Could not delete branch (may not exist or be checked out elsewhere)"
        fi
        SCRIPT_EOF
              chmod +x $out/bin/worktree-remove
      '';
    };

  # Default worktree scripts
  worktreeScripts = mkWorktreeScripts {};

  # Shell hook for worktree mode (orchestrator)
  # Sets up directories and generates config files
  # Uses sibling worktree pattern - main repo is the orchestrator, worktrees are siblings
  worktreeShellHook = {
    mcpConfigOrchestrator,
    mcpConfigShared,
    languages,
    mcps,
    tools,
    devshellsUrl ? "github:Ba-So/nix-devshells",
  }: let
    subtreeFlakeContent = generateSubtreeFlakeContent {
      inherit languages mcps tools devshellsUrl;
    };
    sharedClaudeMd = generateSharedClaudeMd;
    orchestratorClaudeMd = generateOrchestratorClaudeMd;
  in ''
    # Worktree mode setup (sibling pattern)
    _setup_worktree_mode() {
      local project_root
      project_root="$(pwd)"

      # Verify this is a git repository
      if [ ! -d ".git" ]; then
        echo "  Warning: Not a git repository. Worktree commands won't work."
        echo "  Initialize git first: git init"
      fi

      # Create .shared directory
      if [ ! -d ".shared" ]; then
        mkdir -p .shared/.codanna
        echo "  Created .shared/ directory"
      fi

      # Generate .shared/flake.nix
      cat > .shared/flake.nix << 'SUBTREE_FLAKE_EOF'
    ${subtreeFlakeContent}
    SUBTREE_FLAKE_EOF
      echo "  Generated .shared/flake.nix"

      # Copy shared MCP config (without task-master)
      cp ${mcpConfigShared} .shared/.mcp.json
      echo "  Generated .shared/.mcp.json (without task-master)"

      # Generate shared CLAUDE.md
      cat > .shared/CLAUDE.md << 'SHARED_CLAUDE_EOF'
    ${sharedClaudeMd}
    SHARED_CLAUDE_EOF
      echo "  Generated .shared/CLAUDE.md"

      # Create .orchestrator directory
      if [ ! -d ".orchestrator" ]; then
        mkdir -p .orchestrator
        echo "  Created .orchestrator/ directory"
      fi

      # Copy orchestrator MCP config (with task-master)
      cp ${mcpConfigOrchestrator} .orchestrator/.mcp.json

      # Update codanna in orchestrator config to index current directory (.)
      if ${pkgs.jq}/bin/jq -e '.mcpServers.codanna' .orchestrator/.mcp.json &>/dev/null; then
        ${pkgs.jq}/bin/jq '
          .mcpServers.codanna.args = ["serve", ".", "--watch", "--watch-interval", "5"]
        ' .orchestrator/.mcp.json > .orchestrator/.mcp.json.tmp && \
        mv .orchestrator/.mcp.json.tmp .orchestrator/.mcp.json
        echo "  Configured codanna to index current directory"
      fi
      echo "  Generated .orchestrator/.mcp.json (with task-master)"

      # Generate orchestrator CLAUDE.md at root (only if not exists or is a generated file)
      if [ ! -f "CLAUDE.md" ] || grep -q "Orchestrator Agent Instructions" CLAUDE.md 2>/dev/null; then
        cat > CLAUDE.md << 'ORCHESTRATOR_CLAUDE_EOF'
    ${orchestratorClaudeMd}
    ORCHESTRATOR_CLAUDE_EOF
        echo "  Generated CLAUDE.md (orchestrator instructions)"
      else
        echo "  Keeping existing CLAUDE.md (not overwriting user content)"
      fi

      # Create symlink from root to orchestrator config
      if [ ! -L ".mcp.json" ] && [ ! -f ".mcp.json" ]; then
        ln -sf .orchestrator/.mcp.json .mcp.json
        echo "  Linked .mcp.json -> .orchestrator/.mcp.json"
      elif [ -L ".mcp.json" ]; then
        # Update existing symlink
        rm .mcp.json
        ln -sf .orchestrator/.mcp.json .mcp.json
        echo "  Updated .mcp.json symlink"
      else
        # .mcp.json exists as regular file - merge configs
        if command -v ${pkgs.jq}/bin/jq &> /dev/null; then
          ${pkgs.jq}/bin/jq -s '.[0] * .[1]' .mcp.json ${mcpConfigOrchestrator} > .mcp.json.new 2>/dev/null || {
            echo "Warning: Failed to merge .mcp.json, keeping existing file"
            rm -f .mcp.json.new
          }
          [ -f .mcp.json.new ] && mv .mcp.json.new .mcp.json && echo "  Merged orchestrator MCP config into .mcp.json"
        fi
      fi

      # Set CODANNA_INDEX_DIR for shared index
      export CODANNA_INDEX_DIR="$project_root/.shared/.codanna"

      echo "  Worktree mode configured (sibling pattern)"
      echo "  CODANNA_INDEX_DIR=$CODANNA_INDEX_DIR"
    }

    _setup_worktree_mode

    echo "  Worktree commands: worktree-new, worktree-status, worktree-remove"
  '';

  # Shell hook for subtree mode (worker agents)
  # Minimal setup - just sets CODANNA_INDEX_DIR
  # Sibling pattern: worktree is at ../<project>-<branch>/, main project is at ../<project>/
  subtreeShellHook = ''
    # Subtree mode setup (worker agent in sibling worktree)
    _setup_subtree_mode() {
      local project_root
      project_root="$(pwd)"

      # Find the main project's .shared directory
      # In sibling pattern, we're at ../<project>-<branch>/, main is at ../<project>/
      # The .envrc points to ../<project>/.shared, so we can find it from the flake path

      # Try to find .shared in sibling directories
      local found_shared=""
      for sibling in ../*; do
        if [ -d "$sibling/.shared/.codanna" ]; then
          found_shared="$(cd "$sibling/.shared/.codanna" && pwd)"
          break
        fi
      done

      if [ -n "$found_shared" ]; then
        export CODANNA_INDEX_DIR="$found_shared"
        echo "  Using shared codanna index: $CODANNA_INDEX_DIR"
      else
        echo "  Warning: Shared codanna index not found in sibling directories"
        echo "  Run 'direnv allow' in the main project directory first"
      fi
    }

    _setup_subtree_mode
  '';

  # Create a filtered source for worktree flakes
  # Excludes generated directories to avoid copying them to the nix store
  # With sibling pattern, there's no nested mainDir to filter
  mkWorktreeSource = {
    src,
    extraExcludes ? [],
  }: let
    excludedNames =
      [
        ".shared" # Generated by worktree mode
        ".orchestrator" # Generated by worktree mode
        ".direnv" # direnv cache
        "target" # Common build directory (Rust, etc.)
        "node_modules" # Node.js dependencies
        "__pycache__" # Python cache
        ".mypy_cache" # Mypy cache
        ".pytest_cache" # Pytest cache
      ]
      ++ extraExcludes;
  in
    builtins.path {
      path = src;
      name = "worktree-source";
      filter = path: _type: let
        name = baseNameOf path;
        # Always include essential flake files at the root
        isFlakeFile = name == "flake.nix" || name == "flake.lock" || name == ".envrc";
      in
        isFlakeFile || !(builtins.elem name excludedNames);
    };
}
